### ISSUE TITLE
進度條導入 命名問題 文件路徑問題

### ISSUE THREAD

**Issue by tim629** [kevin0929/TestJudge-v2#5]
1.tqdm模塊用於顯示進度條，但是未用到此模塊，如果用不到可以刪除。

2.compile在python我記得是內建函數的名稱，建議改成不與函數衝突的名稱。

3.在get_all_score函數中，使用glob獲取文件列表時，假設文件的名稱符合"P數字.c"的格式。需考慮如果文件命名不符合此格式，會導致獲取失敗。建議在處理文件命名時，添加適當的錯誤處理或檢查文件名的格式。

**Comment by kevin0929** [comment]
這是 chatGPT 的結果嗎 XD。

1. 我會用到 tqdm 來顯示目前已經處理哪些檔案了。
2. 我會採納這個建議，不過你有推薦怎麼命名? 可以嘗試 fork 我的程式下來，改完之後發 PR，改個小地方也好。
3. 所以才說檔名一定要打好QQ，不過我在 dependcies.py 就有處理類似的狀況了，只要不要太離譜基本上都會改成規定的格式。
